from __future__ import annotations

from dataclasses import dataclass


def _escape_string_for_codegen(value: str) -> str:
    """Escape a string for safe inclusion in generated Python code."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


@dataclass
class ModalAppCodeConfig:
    """Configuration for generating the Modal app source code."""

    app_name: str
    python_version: str
    model_requirements: list[str] | None
    extra_pip_packages: list[str] | None
    pip_index_url: str | None
    pip_extra_index_url: str | None
    gpu_config: str | list[str] | None
    memory: int | str
    cpu: int | str
    timeout: int
    modal_secret: str
    wheel_filenames: list[str] | None
    enable_batching: bool
    max_batch_size: int
    concurrent_inputs: int
    target_inputs: int | None
    batch_wait_ms: int
    min_containers: int | None
    max_containers: int | None
    buffer_containers: int | None
    scaledown_window: int | None
    startup_timeout: int | None
    proxy_auth: bool


class ModalAppCodeGenerator:
    """Generate Modal app Python source code from a configuration object."""

    def __init__(self, config: ModalAppCodeConfig) -> None:
        self._config = config

    def generate(self) -> str:
        """Generate the full Modal app module source."""
        parts: list[str] = []
        parts.append(self._render_header_and_setup())
        parts.append(self._render_predict_methods())
        parts.append(self._render_streaming_method())
        return "".join(parts)

    def _render_header_and_setup(self) -> str:
        c = self._config
        secret_str, secrets_arg = self._render_secret_decorator()
        scaling_str = self._render_scaling_args()
        return f'''"""
Modal app for serving MLflow model: {c.app_name}
Auto-generated by mlflow-modal plugin
"""
import modal

app = modal.App("{c.app_name}")

model_volume = modal.Volume.from_name("{c.app_name}-model-volume", create_if_missing=True)
MODEL_DIR = "/model"
{secret_str}
image = (
    modal.Image.debian_slim(python_version="{c.python_version}")
    .uv_pip_install({self._render_uv_pip_install_str()}{self._render_pip_install_kwargs()})
)

@app.cls(
    image=image,
    gpu={self._render_gpu_str()},
    memory={c.memory},
    cpu={c.cpu},
    timeout={c.timeout},
    {scaling_str}
    {secrets_arg}
    volumes={{MODEL_DIR: model_volume}},
)
{self._render_concurrent_decorator()}class MLflowModel:
    @modal.enter()
    def load_model(self):
        import mlflow.pyfunc
        model_volume.reload()
{self._render_wheel_install_code()}
        self.model = mlflow.pyfunc.load_model(MODEL_DIR)

'''

    def _render_pip_install_kwargs(self) -> str:
        """Build pip install kwargs for private repos."""
        c = self._config
        pip_install_kwargs = []
        if c.pip_index_url:
            pip_install_kwargs.append(f'index_url="{_escape_string_for_codegen(c.pip_index_url)}"')
        if c.pip_extra_index_url:
            pip_install_kwargs.append(f'extra_index_url="{_escape_string_for_codegen(c.pip_extra_index_url)}"')

        pip_install_kwargs_str = ", ".join(pip_install_kwargs)
        if pip_install_kwargs_str:
            pip_install_kwargs_str = ", " + pip_install_kwargs_str
        return pip_install_kwargs_str

    def _render_uv_pip_install_str(self) -> str:
        """Render the uv pip install string."""
        c = self._config
        pip_packages = ["mlflow"]
        if c.model_requirements:
            pip_packages.extend(c.model_requirements)
        if c.extra_pip_packages:
            pip_packages.extend(c.extra_pip_packages)
        uv_pip_install_args = [f'"{pkg}"' for pkg in pip_packages]
        # Use multi-line formatting when there are many packages to avoid
        # generating a single line too long for Python to parse
        if len(uv_pip_install_args) > 10:
            uv_pip_install_str = "\n        " + ",\n        ".join(uv_pip_install_args) + ",\n    "
        else:
            uv_pip_install_str = ", ".join(uv_pip_install_args)
        return uv_pip_install_str

    def _render_concurrent_decorator(self) -> str:
        """Render the concurrent decorator."""
        c = self._config
        concurrent_decorator_line = ""
        if (c.concurrent_inputs and c.concurrent_inputs > 1) or c.target_inputs is not None:
            concurrent_args = []
            if c.concurrent_inputs and c.concurrent_inputs > 1:
                concurrent_args.append(f"max_inputs={c.concurrent_inputs}")
            if c.target_inputs is not None:
                concurrent_args.append(f"target_inputs={c.target_inputs}")
            concurrent_decorator_line = f"@modal.concurrent({', '.join(concurrent_args)})\n"
        return concurrent_decorator_line

    def _render_scaling_args(self) -> str:
        """Render the scaling arguments."""
        c = self._config
        scaling_parts = []
        if c.min_containers is not None and c.min_containers > 0:
            scaling_parts.append(f"min_containers={c.min_containers}")
        if c.max_containers is not None:
            scaling_parts.append(f"max_containers={c.max_containers}")
        if c.buffer_containers is not None:
            scaling_parts.append(f"buffer_containers={c.buffer_containers}")
        if c.scaledown_window is not None:
            scaling_parts.append(f"scaledown_window={c.scaledown_window}")
        if c.startup_timeout is not None:
            scaling_parts.append(f"startup_timeout={c.startup_timeout}")

        scaling_str = "\n    ".join(f"{part}," for part in scaling_parts)
        return scaling_str

    def _render_wheel_install_code(self) -> str:
        """Generate wheel installation code if wheels are present."""
        c = self._config
        wheel_install_code = ""
        if c.wheel_filenames:
            wheel_paths = [f"/model/wheels/{whl}" for whl in c.wheel_filenames]
            wheel_install_code = f"""
# Install wheel dependencies from volume
import subprocess
import sys
wheel_files = {wheel_paths}
for whl in wheel_files:
    subprocess.check_call([sys.executable, "-m", "pip", "install", whl, "--quiet"])
"""
        return wheel_install_code

    def _render_gpu_str(self) -> str:
        """Handle GPU config: string, multi-GPU string ("H100:8"), or fallback list."""
        c = self._config
        if not c.gpu_config:
            gpu_str = "None"
        elif isinstance(c.gpu_config, list):
            gpu_str = "[" + ", ".join(f'"{g}"' for g in c.gpu_config) + "]"
        else:
            gpu_str = f'"{c.gpu_config}"'
        return gpu_str

    def _render_predict_methods(self) -> str:
        c = self._config
        if c.enable_batching:
            return f"""
    @modal.batched(max_batch_size={c.max_batch_size}, wait_ms={c.batch_wait_ms})
    def predict_batch(self, inputs: list[dict]) -> list[dict]:
        import pandas as pd
        results = []
        for input_data in inputs:
            df = pd.DataFrame(input_data)
            prediction = self.model.predict(df)
            results.append({{"predictions": prediction.tolist() if hasattr(prediction, 'tolist') else list(prediction)}})
        return results

    {self._render_fastapi_endpoint_decorator()}
    def predict(self, input_data: dict) -> dict:
        return self.predict_batch.local([input_data])[0]
"""

        return f"""
    {self._render_fastapi_endpoint_decorator()}
    def predict(self, input_data: dict) -> dict:
        import pandas as pd
        df = pd.DataFrame(input_data)
        prediction = self.model.predict(df)
         return {{"predictions": prediction.tolist() if hasattr(prediction, "tolist") else list(prediction)}}
"""

    def _render_fastapi_endpoint_decorator(self) -> str:
        """Render the fastapi endpoint decorator."""
        c = self._config
        if c.proxy_auth:
            return '@modal.fastapi_endpoint(method="POST", requires_proxy_auth=True)'
        return '@modal.fastapi_endpoint(method="POST")'

    def _render_secret_decorator(self) -> str:
        """Build secret reference if specified (escape for safe code generation)"""
        c = self._config
        secret_str = ""
        secrets_arg = ""
        if c.modal_secret:
            secret_str = f'pip_secret = modal.Secret.from_name("{_escape_string_for_codegen(c.modal_secret)}")\n'
            secrets_arg = "secrets=[pip_secret],"
        return secret_str, secrets_arg

    def _render_streaming_method(self) -> str:
        return f"""
    {self._render_fastapi_endpoint_decorator()}
    def predict_stream(self, input_data: dict):
        from fastapi.responses import StreamingResponse
        import json

        def generate():
            # Try streaming prediction first, fall back to regular prediction
            try:
                if hasattr(self.model, 'predict_stream'):
                    for chunk in self.model.predict_stream(input_data):
                        yield f"data:{{json.dumps(chunk)}}\\n\\n"
                    yield "data: [DONE]\\n\\n"
                    return
            except Exception:
                # Model doesn't support streaming, fall back to regular prediction
                pass

            # Fall back to regular prediction for non-streaming models
            import pandas as pd
            df = pd.DataFrame(input_data)
            prediction = self.model.predict(df)
            yield f"data: {{json.dumps({{'predictions': prediction.tolist() if hasattr(prediction, 'tolist') else list(prediction)}})}}\\n\\n"
            yield "data: [DONE]\\n\\n"

        return StreamingResponse(generate(), media_type="text/event-stream")
"""


def generate_modal_app_code(config: ModalAppCodeConfig) -> str:
    """Convenience API to generate Modal app code from a config."""
    return ModalAppCodeGenerator(config).generate()
